### ISSUE TITLE
Temporary Files

### ISSUE THREAD

**Issue by 0vm** [Varshithvhegde/FreeShare#2]
I strongly recommend implementing a time limit to enhance the security. Without a time restriction, there may be a risk similar to what has been seen with Lightshot, where people could guess screenshot codes to access sensitive information. A 48-hour limit would be a good starting point, but the crucial issue to address is that, as it currently stands, anyone's files can be brute-forced in just a few minutes using a couple of proxies.

**Comment by 0vm** [comment]
Nevermind, I just noticed the section on "Future Plans". I suggest making that the top priority since privacy should be the primary focus.

**Comment by Varshithvhegde** [comment]
I am working on implemeting like allowing 5-10 wrong try per ip . Something like that!!!.

**Comment by 0vm** [comment]
5-10 Will not make a difference, 1000 proxies is $30 monthly. Best bet is to add a captcha as going through 99999 combinations with 5c per captcha is going to be expensive. And add that with rate-limiting, and you are set for production, but you still do need temporary storage.
